name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Checkout the repository to access Dockerfile
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (or other Docker registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-actions-app-image:latest --platform linux/amd64 .

      # Push the Docker image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-actions-app-image:latest

      - name: Make POST Curl Request to Deploy
        run: curl -X POST http://${{ secrets.DEPLOY_IP }}/deploy
